@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class AddressBook
Class ModelManager
Class UserPrefs

Class UniquePersonList
' Person with ClubTrack-specific primitive attributes
Class Person {
  - yearOfStudy : int
  - faculty : String
}
Class Address
Class Email
Class Name
Class Phone
Class Tag
Class Points

Class I #FFFFFF
}

' AB3-style outer ref (keep identical)
Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

' Interfaces and realizations (keep identical order/direction)
AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

' Collections and compositions
AddressBook *--> "1" UniquePersonList
UniquePersonList --> "~* all" Person
Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address
Person *--> "*" Tag
Person *--> Points

Person -[hidden]up--> I
UniquePersonList -[hidden]right-> I

Name -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> Email

' Filtered list exposure
ModelManager --> "~* filtered" Person

' Show just Person attributes (AB3 theme hides members globally)
show Person attributes
hide Person methods
skinparam ClassAttributeFontColor white
@enduml
